### ISSUE TITLE
Device is unsupported error on iPhone XR and iPhone 12

### ISSUE THREAD

**Issue by maskrcnnuser** [Frost-Lee/insulin_calculator#1]
Hi @Frost-Lee 

Thanks for the repository. I am trying to run this on iPhone XR and iPhone 12 but the first thing I get is "Sorry, but your device is unsupported". Could you please help me understand what is going wrong here? 

Thanks.

**Comment by Frost-Lee** [comment]
The `master` branch only keeps the universal logic of the app instead of interfaces. You can switch to the `product` branch to see its interface. Be sure to use a physical device instead of simulators.

**Comment by maskrcnnuser** [comment]
Thanks @Frost-Lee for the quick response. I am using the real devices. I have got two iPhones and have tried to connect both of them. As soon as the code is compiled, it's loaded on the phone and the error message appears.

**Comment by Frost-Lee** [comment]
Please switch to the `product` branch (`git checkout product`) before you test the app on your device. The `master` branch don't have functional interfaces, the interface showing "device not supported" is just a placeholder. You can checkout the storyboard for details.

**Comment by maskrcnnuser** [comment]
> Please switch to the `product` branch (`git checkout product`) before you test the app on your device. The `master` branch don't have functional interfaces, the interface showing "device not supported" is just a placeholder. You can checkout the storyboard for details.

Thanks a lot once again for a prompt response. I will follow your suggested steps and see what happens. Thanks again.
